# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ericfitz.agentbus
PackageVersion: 1.14.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: agentbus.exe
  PortableCommandAlias: agentbus
UpgradeBehavior: install
Commands:
- agentbus
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ericfitz/agentbus/releases/download/v1.14.2/agentbus-v1.14.2-windows-amd64.zip
  InstallerSha256: D0FB621860246FB606C51CAA148F7603DAA92D99B70814FD7C2317478D0B0D54
- Architecture: arm64
  InstallerUrl: https://github.com/ericfitz/agentbus/releases/download/v1.14.2/agentbus-v1.14.2-windows-arm64.zip
  InstallerSha256: 49C6239195912B5E407C2CC74652025C28EC72E852389B822CF121EB46C87E80
ManifestType: installer
ManifestVersion: 1.12.0
